export const GET_ALL_SCHOOLS = "get_all_schools"
export const GET_SCHOOL_DETAILS = "get_school_detals"
export const GET_ALL_COURSE_PREREQUISITES = "get_all_course_prerequisites"
export const GET_ALL_SCHOOL_OUTLINES  = "get_all_school_outlines"
export const GET_ALL_SCHOOL_INSTRUCTORS = "get_all_school_instructors"
export const GET_ALL_SCHOOL_CURRICULUMS = "get_all_schools_curriculums"
export const GET_ALL_COURSE_OUTLINE_DETAILS = "get_all_course_outline_details"
export const GET_LESSON_VIDEO_DETAILS = "get_lesson_video_details"